### ISSUE TITLE
Sauce Post Request Body

### ISSUE THREAD

**Issue by mwhite192** [mwhite192/Web-Developer-P6#1]
@AccessiT3ch - Hey Conor!  I have a question.  In the line of code, I understand we used these lines to create a new user and add that user to the database.  I am working on the sauce everything now and in the post request the same concept applies to save new sauce to the database; however, the technical requirements state that the sauce request body should be as follows:
`app.post(/api/sauces', (req, res, next) => {
    const sauce = new Sauce({
        sauce: String,
        image: File
});`
My question is where did 'sauce' come from if we are creating a new sauce?  Don't we have to follow the same concept we used to create the user?  Or could it be the creator of the document just didn't want to list/type all the information?

https://github.com/mwhite192/Web-Developer-P6/blob/e76ce5ffae85a8a68630dd7a3fd0c8896b405689/backend/controllers/user.js#L8-L11

**Comment by AccessiT3ch** [comment]
@mwhite192 In this case, `sauce` is an instance of `Sauce`, instantiated with `new Sauce(...)`. `Sauce` should be exported from your `models/sauce.js` file. Does that answer your question? 🙂

**Comment by mwhite192** [comment]
@AccessiT3ch - yep it does!  Thanks Conor!
