### ISSUE TITLE
Uploading image from form

### ISSUE THREAD

**Issue by mwhite192** [mwhite192/Web-Developer-P6#2]
@AccessiT3ch - Hey Conor!  It seems I am having issues with uploading the image file to the server.  Every time I complete the form, I check out the payload and the image still says binary.  I have configured multer correctly (I think), applied it to the post route, and they payload still says binary.  Without giving me too much, may I use a life line :) ? Any hint you can provide would really helpful because your the best!

**Comment by AccessiT3ch** [comment]
@mwhite192 Have you tried console logging in the backend controller to see what `req.file` is? Multer should be saving image files to an `images` directory, which you'll also want to serve up via a static route in the `app.js`.

(it also looks like your [`new Sauce()`](https://github.com/mwhite192/Web-Developer-P6/blob/master/backend/controllers/sauce.js#L11) is using the wrong prop name for the image file path)

**Comment by mwhite192** [comment]
@AccessiT3ch - I think I understand. So for new Saice() imageUrl should be the prop name there correct? If that’s so why I’m the documentation it says the request body for the post request should be sauce: String and image: file?

**Comment by mwhite192** [comment]
@AccessiT3ch - another question. The image prop in the form data in the network tab says (binary). This just means I’m not converting my image correctly upon upload correct?

**Comment by AccessiT3ch** [comment]
> So for new Saice() imageUrl should be the prop name there correct? 

Correct, which should match the mongo schema defined in the `models/sauce.js`.

> If that’s so why I’m the documentation it says the request body for the post request should be sauce: String and image: file?

This is describing the what the body of the fetch POST request (which is different than the Sauce instance created within the `controllers/sauce.js` function), which is [being handled by the frontend](https://github.com/mwhite192/Web-Developer-P6/blob/master/src/app/services/sauces.service.ts#L53-L60).

> The image prop in the form data in the network tab says (binary). 

This sounds right. To my understanding Multer is supposed to be receiving that binary version of the file and saving it to an `images` folder as `jpg` or `png` files before saving `request.image` as a JSON formatted object (which, should include some metadata about the image, not the image itself), which is available on the request parameter of your route controller function.

> This just means I’m not converting my image correctly upon upload correct?

You shouldn't have to mess with the frontend at all with this project! :)

@mwhite192 Does that all make sense?

**Comment by mwhite192** [comment]
@AccessiT3ch - this made perfect sense thank you!
